# Changes here will be overwritten by Copier
_commit: v1.4.3
_src_path: gh:lincc-frameworks/python-project-template
author_email: vyp6w52@mail.ru
author_name: Rizvan Ganeyev
create_example_module: true
custom_install: true
include_benchmarks: true
include_docs: true
include_notebooks: false
mypy_type_checking: none
package_name: model_fit_api
preferred_linter: black
project_license: MIT
project_name: model-fit-api
use_gitlfs: none
use_isort: false
